#--------------------------------customer-------------------------
###
get http://localhost:8091/customer/
###
post http://localhost:8091/customer/
Content-Type: application/json

{
  "customerName": "ishwarya",
  "customerAddress": "chennai",
  "customerStatus": "true",
  "customerContact": 7876543210,
  "userName": "ish",
  "password": "ish"
}
###
get http://localhost:8091/customer/users/sumathi
###
put http://localhost:8091/customer/
Content-Type: application/json

  {
    "customerId": 6789009,
    "customerName": "sumathi",
    "customerAddress": "salem",
    "customerStatus": "true",
    "customerContact": 9994646398,
    "userName": "sumathi",
    "password": 2345
  }
###
delete http://localhost:8091/customer/
Content-Type: application/json

{
    "customerId": 868687,
    "customerName": "priya",
    "customerAddress": "Dharmapuri",
    "customerStatus": "true",
    "customerContact": 9989008789,
    "userName": "pri",
    "password": 6789
  }

#--------------------------account---------------------------
###
get http://localhost:8092/account/
###
post http://localhost:8092/account/
Content-Type: application/json

{
    "accountType":"Savings Deposit",
    "accountNumber":8989899899,
    "accountBalance":90000,
    "accountStatus":true,
    "customer":3
}
###
get http://localhost:8092/account/2

#----------------------------payee------------------------------------------
###
post http://localhost:8093/payee/
Content-Type: application/json

{
  "payeeName":"uma",
  "payeeAccountNum":1234567890,
  "rootAccount":8989899899
}
###
get http://localhost:8093/payee/
###
get http://localhost:8093/payee/sender/9876543210
###
get http://localhost:8093/payee/name/dhinesh
###
put http://localhost:8093/payee/
Content-Type: application/json

{
    "payeeId": 1,
    "payeeName": "uma",
    "payeeAccountNum": 1234567890,
    "rootAccount": 9876543210
}
------------------------------------Transaction-----------------------------
###
POST http://localhost:8094/transfer/
Content-Type: application/json

{
  "transactionFrom":9876543210,
  "transactionTo":4467587587 ,
  "transactionAmount":100,
  "transactionType":"IMPS"
}
###
get http://localhost:8094/transfer/
###
get http://localhost:8094/transfer/transactiontype/imps
###
get http://localhost:8094/transfer/transactiondate/2024-12-04
###
get http://localhost:8094/transfer/trfromanddate/4467587587/2024-12-02
###
get http://localhost:8094/transfer/trfrom/4467587587